<?php
/**
 * @file
 * Code for the country_data feature.
 */

include_once 'country_data.features.inc';

function country_data_theme() {
	return array(
		'country_data_contact_person' => array(
			'render element' => 'element',
			'template' => 'templates/country-data-contact-person',
			'variables' => array('contact_person' => NULL, 'treaty' => NULL),
			'path' => drupal_get_path('module', 'country_data'),
		),
	);
}

/**
 * Implements hook_views_pre_render().
 */
function country_data_views_pre_render(&$view) {
  if ($view->name == 'ws_member_parties' && $view->current_display == 'services_1') {
    foreach($view->result as $row) {
      if(!empty($row->field_field_party_date_1[0])) {
        $d = strtotime($row->field_field_party_date_1[0]['raw']['value']);
        $row->field_field_party_date_1[0]['rendered']['#markup'] = date('Ymd', $d);
      }
      if(!empty($row->field_field_party_date_2)) {
        $d = strtotime($row->field_field_party_date_2[0]['raw']['value']);
        $row->field_field_party_date_2[0]['rendered']['#markup'] = date('Ymd', $d);
      }
    }
  }

}