languages:
  Ruby: false
  JavaScript: true
  PHP: true
  Python: false
exclude_paths:
- conf/**/*
- content/**/*
- drush/**/*
- patches/**/*
- results/**/*
- scripts/**/*
- scripts/*
- tests/*
- tests/**/*
- docroot/includes/**/*
- docroot/includes/*
- docroot/misc/*
- docroot/misc/**/*
- docroot/modules/**/*
- docroot/profiles/**/*
- docroot/scripts/*
- docroot/themes/**/*
- docroot/sites/default/*
- docroot/sites/all/libraries/**/*
- docroot/sites/all/modules/contrib/**/*
- docroot/sites/all/themes/zen/**/*
- docroot/authorize.php
- docroot/cron.php
- docroot/index.php
- docroot/install.php
- docroot/test.php
- docroot/update.php
- docroot/xmlrpc.php

