<?php
/**
 * @file
 * Code for the goal feature.
 */

include_once 'goal.features.inc';

define('GOAL_SOURCE_SDG', 1753);
define('GOAL_SOURCE_AICHI', 1738);
define('GOAL_SOURCE_GEG', 1739);
define('GOAL_SOURCE_MDG', 1740);
define('GOAL_TYPE_GOAL', 1734);
define('GOAL_TYPE_TARGET', 1737);
define('GOAL_TYPE_INDICATOR', 1735);

/**
 * Implements hook_menu().
 */
function goal_menu() {

  $items = array();

  $items['goal/autocomplete/field_sdg_goals'] = array(
    'title' => 'SDG goals Autocomplete',
    'page callback' => 'sdg_goals_autocomplete_callback',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Menu callback for SDG goals autocomplete.
 *
 * @param $string
 */
function sdg_goals_autocomplete_callback($string) {
  $matches = [];

  $args = func_get_args();
  $string = implode('/', $args);

  $q = db_select('node', 'n');
  $q->innerJoin('field_data_field_goal_source', 'gs', 'n.nid = gs.entity_id');
  $q->fields('n', ['nid', 'title']);
  $q->condition('gs.field_goal_source_tid', GOAL_SOURCE_SDG); /* SDG goals */
  $q->condition('n.title', '%' . db_like($string) . '%', 'LIKE');
  $items = $q->execute()->fetchAllKeyed();
  foreach ($items as $nid => $title) {
    $matches["{$title} ({$nid})"] = '<div class="reference-autocomplete">' . $title . '</div>';
  }

  drupal_json_output($matches);
}

function goal_theme() {
  return array(
    'goals_listing' => array(
      'render element' => 'element',
      'template' => 'templates/goals-listing',
      'variables' => array('goals'),
      'path' => drupal_get_path('module', 'goal'),
    ),
    'goal_text_tags' => array(
      'render element' => 'element',
      'template' => 'templates/goal-text-tags',
      'variables' => array('tags'),
      'path' => drupal_get_path('module', 'goal'),
    ),
    'goal_text' => array(
      'render element' => 'element',
      'template' => 'templates/goal-text',
      'variables' => array('goal', 'base_goal_url'),
      'path' => drupal_get_path('module', 'goal'),
    ),
    'goal_target' => array(
      'render element' => 'element',
      'template' => 'templates/goal-target',
      'variables' => array('goal', 'target', 'base_goal_url'),
      'path' => drupal_get_path('module', 'goal'),
    ),
    'goal_target_indicator' => array(
      'render element' => 'element',
      'template' => 'templates/goal-target-indicator',
      'variables' => array('goal', 'target', 'indicator', 'base_goal_url'),
      'path' => drupal_get_path('module', 'goal'),
    ),
    'goal_target_indicator_specific' => array(
      'render element' => 'element',
      'template' => 'templates/goal-target-indicator-specific',
      'variables' => array('goal', 'target', 'indicator', 'specific', 'base_goal_url'),
      'path' => drupal_get_path('module', 'goal'),
    ),
    'goal_related_content' => array(
      'render element' => 'element',
      'template' => 'templates/goal-related-content',
      'variables' => array('items'),
      'path' => drupal_get_path('module', 'goal'),
    ),
  );
}

/**
 * Implements hook_block_info().
 */
function goal_block_info() {
  $blocks = [
    'goal_related_content_block' => [
      'info' => t('Goal related content'),
      'cache' => DRUPAL_NO_CACHE,
      'status' => 1,
      'region' => 'content',
      'visibility' => BLOCK_VISIBILITY_NOTLISTED,
      'pages' => '',
    ],
  ];
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function goal_block_view($delta = '') {
  $block = [];
  switch ($delta) {
    case 'goal_related_content_block':
      $block['content'] = '';
      $ob = menu_get_object();
      if (!empty($ob) && $ob->type == 'goal') {
        drupal_add_js(drupal_get_path('module', 'goal') . '/js/goal.js');
        drupal_add_library('informea', 'scrollto');
        drupal_add_library('informea', 'smallipop');
        drupal_add_css(drupal_get_path('module', 'goal') . '/styles/goal.css');

        $ob_w = entity_metadata_wrapper('node', $ob);
        $type = $ob_w->field_goal_type->value();
        $source = $ob_w->field_goal_source->value();
        switch ($type->tid) {
          case GOAL_TYPE_GOAL:
            $targets = _get_goal_children($source, $ob, 'Target');
            if (!empty($targets)) {
              $block['content'] = sprintf('<div><h3>%s</h3>', t('Targets'));
              foreach ($targets as $target) {
                $indicators = _get_goal_children($source, $target, 'Indicator');
                foreach ($indicators as $indicator) {
                  $indicator->specific_indicators = _get_goal_children($source, $indicator, 'Indicator');
                }
                $target->indicators = $indicators;
                $block['content'] .= theme('goal_target', [
                  'goal' => $ob,
                  'target' => $target,
                  'base_goal_url' => url('taxonomy/term/' . $source->tid, ['absolute' => TRUE,])
                ]);
              }
              $block['content'] .= '</div>';
            }
            break;

          case GOAL_TYPE_TARGET:
            $indicators = _get_goal_children($source, $ob, 'Indicator');
            if (!empty($indicators)) {
              $parent = $ob_w->field_parent_goal->value();
              if (!empty($parent) && is_array($parent)) {
                $parent = reset($parent);
              }
              $block['content'] = sprintf('<div><h3>%s</h3>', t('Indicators'));
              foreach ($indicators as $indicator) {
                $indicator->specific_indicators = _get_goal_children($source, $indicator, 'Indicator');
                $block['content'] .= theme('goal_target_indicator', [
                  'goal' => $parent,
                  'target' => $ob,
                  'indicator' => $indicator,
                  'base_goal_url' => url('taxonomy/term/' . $source->tid, ['absolute' => TRUE,])
                ]);
              }
              $block['content'] .= '</div>';
            }
            break;

          case GOAL_TYPE_INDICATOR:
            $specific_indicators = _get_goal_children($source, $ob, 'Indicator');
            if (!empty($specific_indicators)) {
              $parent = $ob_w->field_parent_goal->value();
              if (!empty($parent) && is_array($parent)) {
                $parent = reset($parent);
              }

              $parent_w = entity_metadata_wrapper('node', $parent);
              $parent2 = $parent_w->field_parent_goal->value();
              if (!empty($parent2) && is_array($parent2)) {
                $parent2 = reset($parent2);
              }

              $block['content'] = sprintf('<div><h3>%s</h3>', t('Specific indicators'));
              foreach ($specific_indicators as $specific_indicator) {
                $block['content'] .= theme('goal_target_indicator_specific', [
                  'goal' => $parent2,
                  'target' => $parent,
                  'indicator' => $ob,
                  'specific_indicator' => $specific_indicator,
                  'base_goal_url' => url('taxonomy/term/' . $source->tid, ['absolute' => TRUE,])
                ]);
              }
              $block['content'] .= '</div>';
            }
            break;
        }
        $items = goal_get_related_content($ob->nid);
        if (!empty($items)) {
          $block['content'] .= sprintf('<div><h3>%s</h3>', t('Related content'));
          $block['content'] .= theme('goal_related_content', array('items' => $items));
          $block['content'] .= '</div>';

        }
      }
      break;
  }
  return $block;
}

function goal_get_related_content($goal_nid) {
  $return = [];
  $nids = db_select('field_data_field_sdg_goals', 'g')
    ->fields('g', ['entity_id', 'bundle'])
    ->condition('g.bundle', ['national_report_paragraph', 'treaty_article', 'treaty_paragraph' , 'decision_paragraph'], 'IN')
    ->condition('g.field_sdg_goals_target_id', $goal_nid)
    ->execute()->fetchAllKeyed();
  if (!empty($nids)) {
    // Get the national reports
    $q = db_select('field_data_field_parent_national_report', 'p');
    $q->innerJoin('field_data_field_treaty', 't', 'p.field_parent_national_report_target_id = t.entity_id');
    $q->fields('p', ['entity_id', 'field_parent_national_report_target_id'])
      ->fields('t', ['field_treaty_target_id'])
      ->condition('p.entity_id', array_keys($nids), 'IN');
    $paragraphs = $q->execute()->fetchAll();
    foreach ($paragraphs as $paragraph) {
      $treaty_id = $paragraph->field_treaty_target_id;
      $national_report_id = $paragraph->field_parent_national_report_target_id;
      if (empty($return[$treaty_id])) {
        $treaty = node_load($treaty_id);
        $treaty->national_reports = [];
        $return[$treaty_id] = $treaty;
      }
      if (empty($return[$treaty_id]->national_reports[$national_report_id])) {
        $national_report = node_load($national_report_id);
        $national_report->children = [];
        $return[$treaty_id]->national_reports[$national_report_id] = $national_report;
      }
      $paragraph = node_load($paragraph->entity_id);
      $return[$treaty_id]->national_reports[$national_report_id]->children[] = $paragraph;
    }
    // Get the treaty articles
    $q = db_select('field_data_field_parent_treaty_article', 'a');
    $q->innerJoin('field_data_field_treaty', 't', 'a.field_parent_treaty_article_target_id = t.entity_id');
    $q->fields('a', ['entity_id', 'field_parent_treaty_article_target_id'])
      ->fields('t', ['field_treaty_target_id'])
      ->condition('a.entity_id', array_keys($nids), 'IN');
    $paragraphs = $q->execute()->fetchAll();
    foreach ($paragraphs as $paragraph) {
      $treaty_id = $paragraph->field_treaty_target_id;
      $article_id = $paragraph->field_parent_treaty_article_target_id;
      if (empty($return[$treaty_id])) {
        $treaty = node_load($treaty_id);
        $treaty->national_reports = [];
        $return[$treaty_id] = $treaty;
      }
      if (empty($return[$treaty_id]->treaty_articles[$article_id])) {
        $article = node_load($article_id);
        $article->children = [];
        $return[$treaty_id]->treaty_articles[$article_id] = $article;
      }
      $paragraph = node_load($paragraph->entity_id);
      $return[$treaty_id]->treaty_articles[$article_id]->children[] = $paragraph;
    }
 // Get the decisions
    $q = db_select('field_data_field_parent_decision  ', 'p');
    $q->innerJoin('field_data_field_treaty', 't', 'p.field_parent_decision_target_id  = t.entity_id');
    $q->fields('p', ['entity_id', 'field_parent_decision_target_id '])
      ->fields('t', ['field_treaty_target_id'])
      ->condition('p.entity_id', array_keys($nids), 'IN');
    $paragraphs = $q->execute()->fetchAll();
    foreach ($paragraphs as $paragraph) {
      $treaty_id = $paragraph->field_treaty_target_id;
      $decision_id = $paragraph->field_parent_decision_target_id ;
      if (empty($return[$treaty_id])) {
        $treaty = node_load($treaty_id);
        $treaty->decisions = [];
        $return[$treaty_id] = $treaty;
      }
      if (empty($return[$treaty_id]->decisions[$decision_id])) {
        $decision =node_load($decision_id);
        $decision->children=[];
        $return[$treaty_id]->decisions[$decision_id] = $decision;
      }
      $paragraph = node_load($paragraph->entity_id);
      $return[$treaty_id]->decisions[$decision_id]->children[] = $paragraph;
    }
  }

  $q = db_select('field_data_field_sdg_goals', 'g');
  $q->innerJoin('field_data_field_treaty', 't', 'g.entity_id  = t.entity_id');
  $q->fields('g', ['entity_id'])
    ->fields('t', ['field_treaty_target_id'])
    ->condition('g.bundle', 'document')
    ->condition('g.field_sdg_goals_target_id', $goal_nid);

  $documents = $q->execute()->fetchAll();
  foreach ($documents as $document) {
    $treaty_id = $document->field_treaty_target_id;
    if (empty($return[$treaty_id])) {
      $treaty = node_load($treaty_id);
      $treaty->documents = [];
      $return[$treaty_id] = $treaty;
    }
    $document = node_load($document->entity_id);
    $return[$treaty_id]->documents[] = $document;
  }

  return $return;
}

function goal_preprocess_goal_target_indicator(&$variables) {
  if (arg(0) == 'node' && !empty(arg(1)) && is_numeric(arg(1))) {
    $goal = is_array($variables['goal']) ? reset($variables['goal']) : $variables['goal'];
    $source = $goal->field_goal_source;
    if (!empty($source) && !empty($source[LANGUAGE_NONE])) {
      $variables['theme_hook_suggestions'][] = 'goal_target_indicator__' . $source[LANGUAGE_NONE][0]['tid'];
    }
  }
  else {
    $variables['theme_hook_suggestions'][] = 'goal_target_indicator__' . arg(2);
  }
}

function _get_goal_source_goals($source, $type_of_goals) {
  if (empty($source) || empty($type_of_goals)) {
    return array();
  }

  $goal_type_tid = NULL;
  if ($goal_type = taxonomy_get_term_by_name($type_of_goals, 'type_of_goal')) {
    $goal_type_tid = reset($goal_type)->tid;
  }

  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'goal')
    ->propertyCondition('status', NODE_PUBLISHED)
    ->fieldCondition('field_goal_source', 'tid', $source->tid)
    ->fieldCondition('field_goal_type', 'tid', $goal_type_tid);
  
  $result = $query->execute();
  $ret = !empty($result['node']) ? $result['node'] : [];

  if (!empty($ret)) {
    $q = db_select('field_data_field_sorting_order', 'o')
      ->fields('o', ['entity_id', 'field_sorting_order_value'])
      ->condition('o.entity_id', array_keys($ret), 'IN');
    $sorting_order = $q->execute()->fetchAllKeyed();

    usort($ret, function ($a, $b) use ($sorting_order) {
      $sorting_a = !empty($sorting_order[$a->nid]) ? $sorting_order[$a->nid] : -1;
      $sorting_b = !empty($sorting_order[$b->nid]) ? $sorting_order[$b->nid] : -1;
      return ($sorting_a < $sorting_b) ? -1 : 1;
    });
  }

  return $ret;
}

function _get_goal_children($source, $parent, $type_of_goals) {
  $nodes = array();
  $query = new EntityFieldQuery();

  $goal_type_tid = NULL;
  if ($goal_type = taxonomy_get_term_by_name($type_of_goals, 'type_of_goal')) {
    $goal_type_tid = reset($goal_type)->tid;
  }

  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'goal')
    ->propertyCondition('status', NODE_PUBLISHED)
    ->fieldCondition('field_goal_source', 'tid', $source->tid)
    ->fieldCondition('field_goal_type', 'tid', $goal_type_tid)
    ->fieldCondition('field_parent_goal', 'target_id', $parent->nid)
    ->propertyOrderBy('title', 'ASC');

  if ($result = $query->execute()) {
    $nodes = $result['node'];
  }

  return $nodes;
}

function goal_taxonomy_term_view($term, $view_mode, $langcode) {
  if ($term->vocabulary_machine_name == 'goal_sources' && $view_mode == 'full') {
    drupal_add_js(drupal_get_path('module', 'goal') . '/js/goal.js');
    drupal_add_library('informea', 'scrollto');
    drupal_add_library('informea', 'smallipop');
    drupal_add_css(drupal_get_path('module', 'goal') . '/styles/goal.css');
    if ($term->tid == GOAL_SOURCE_GEG) {
      // Magic number for GEG. We only show the view
      hide($term->content);
    }

    $goals = _get_goal_source_goals($term, 'Goal');
    foreach ($goals as $goal) {
      $targets = _get_goal_children($term, $goal, 'Target');
      foreach ($targets as $target) {
        $indicators = _get_goal_children($term, $target, 'Indicator');
        foreach ($indicators as $indicator) {
          $indicator->specific_indicators = _get_goal_children($term, $indicator, 'Indicator');
        }
        $target->indicators = $indicators;
      }
      $goal->targets = $targets;
    }
    $term->content['goals'] = array(
      '#type' => 'item',
      '#weight' => 10,
      '#markup' => theme(
        'goals_listing', array('term' => $term, 'goals' => $goals)
      ),
    );
  }
}

function goal_link($node, $suffix = '') {
  $wrapper = entity_metadata_wrapper('node', $node);
  $goal = $wrapper->field_goal_source->value();
  return url('taxonomy/term/' . $goal->tid . $suffix);
}

/**
 * Provide goal icon for target or indicator.
 */
function goal_get_icon($entity, $output) {
  static $cache = [];
  if ($output) {
    return $output;
  }
  $ew = entity_metadata_wrapper('node', $entity);
  $goal_type = $ew->field_goal_type->value();
  if (!$goal_type) {
    return '';
  }
  // Goal = 1734.
  if ($goal_type->tid == GOAL_TYPE_GOAL) {
    return '';
  }
  $goal = $ew->field_parent_goal->value();
  if (!$goal) {
    return ;
  }
  // Check for target or indicator broken parent.
  if (!$goal[0]) {
    return '';
  }
  $parent_nid = $goal[0]->nid;
  if (isset($cache[$parent_nid])) {
    return $cache[$parent_nid];
  }
  $pw = entity_metadata_wrapper('node', $goal[0]);
  $icons = $pw->field_images->value();
  if (!$icons) {
    // Check parent of parent icon.
    $goal = $pw->field_parent_goal->value();
    if ($goal) {
      $pw = entity_metadata_wrapper('node', $goal[0]);
      $icons = $pw->field_images->value();
    }
  }
  $cache[$parent_nid] = '';
  if ($icons) {
    $cache[$parent_nid] = empty($icons[0]) ? null : theme('image_style', array('style_name' => 'thumbnail', 'path' => $icons[0]['uri']));
  }
  return $cache[$parent_nid];
}

/**
 * Implements hook_node_presave().
 */
function goal_node_presave($node) {
  if ($node->type == 'goal') {
    // Populate field_sorting_date.
    if (isset($node->created)) {
      $timezone = date('e', $node->created);
      $node->field_sorting_date[LANGUAGE_NONE][0] = [
        'value' => date('Y-m-d h:i:s', $node->created),
        'timezone' => $timezone,
        'timezone_db' => $timezone,
      ];
    }
  }
}
