<?php
/**
 * @file
 * Code for the InforMEA Topics feature.
 */

include_once 'informea_topics.features.inc';
include_once 'blocks/topic_switch_region.block.inc';

/**
 * Implements hook_block_info().
 */
function informea_topics_block_info() {
  return [
    'topic_switch_region' => [
      'info' => t('Browse by Region'),
      'cache' => DRUPAL_CACHE_PER_PAGE,
    ],
  ];
}

/**
 * Implements hook_block_view().
 */
function informea_topics_block_view($delta = '') {
  $block = [];
  switch ($delta) {
    case 'topic_switch_region':
      return informea_topics_topic_switch_region_block_view();
      break;
  }
  return $block;
}

/**
 * Implements hook_taxonomy_term_view().
 */
function informea_topics_taxonomy_term_view($term, $view_mode, $langcode) {
  if ($view_mode == 'full') {
    $vocabulary = taxonomy_vocabulary_machine_name_load('mea_topic');
    if ($term->vid == $vocabulary->vid) {
      // Redirect the default term page to topic panel page.
      drupal_goto('topics/' . strtolower(str_replace(' ', '-', $term->name_original)));
    }
  }
}

/**
 * Page title for topic page.
 */
function informea_topics_page_title() {
  $topic_id = _geographic_region_page_get_argument('topic');
  if (!empty($topic_id)) {
    $vocabulary = taxonomy_vocabulary_machine_name_load('mea_topic');
    $terms = entity_load('taxonomy_term', FALSE, ['vid' => $vocabulary->vid]);
    $options = [];
    $title = '';
    foreach ($terms as $term) {
      if (!empty($term->field_published[LANGUAGE_NONE][0]['value'])) {
        if ($term->tid == $topic_id) {
          $title = sprintf('%s <span class="sr-only">%s</span>', t('Discover environmental information in'), $term->name);
        }
        $options[url('/taxonomy/term/' . $term->tid)] = $term->name;
      }
    }
    if (!empty($options)) {
      return [
        '#type' => 'select',
        '#options' => $options,
        '#default_value' => url('/taxonomy/term/' . $topic_id),
        '#prefix' => '<h1>' . $title . '</h1>',
        '#attributes' => ['onChange' => 'window.location.href=this.value', 'class' => ['use-select-2'], 'id' => 'edit-geographic-region'],
      ];
    }
  }
  return NULL;
}
