<?php
/**
 * @file
 * Code for the Geographic region feature.
 */

include_once 'geographic_region.features.inc';

/**
 * Implements hook_block_info().
 */
function geographic_region_block_info() {
  return [
    'region_page_title' => [
      'info' => t('Page title for regional page'),
      'status' => 1,
      'region' => 'navigation',
      'weight' => -56,
      'visibility' => BLOCK_VISIBILITY_LISTED,
      'pages' => 'regions/*',
      'cache' => DRUPAL_CACHE_PER_PAGE,
    ],
    'region_switch_topic' => [
      'info' => t('Browse by Environmental Topic'),
      'cache' => DRUPAL_CACHE_PER_PAGE,
    ],
    'region_downloadable_documents' => [
      'info' => t('Downloadable documents'),
      'cache' => DRUPAL_CACHE_PER_PAGE,
    ],
  ];
}

/**
 * Retrieve treaties node ids filtered by region and (optional) by topic.
 *
 * @param int $region_id
 *  Region term tid.
 * @param null|int $topic_id
 *  Topic term tid.
 *
 * @return array
 *  Array containing node ids.
 */
function _get_regional_treaties($region_id, $topic_id = NULL) {
  $treaties = [];
  /** @var \view $view */
  $view = views_get_view('regional_treaties');
  if (is_object($view)) {
    $view->set_arguments([$region_id, $topic_id]);
    $view->set_display('block');
    $view->set_items_per_page(0);
    $view->pre_execute();
    $view->execute();
    foreach ($view->result as $result) {
      $treaties[] = $result->nid;
    }
  }
  return $treaties;
}

/**
 * Executes an entity field count query and returns the count of nodes filtered
 * by region and other fields.
 *
 * @param string $content_type
 *  The value of the bundle query condition.
 * @param int $region_id
 *  Region term tid.
 * @param null|int $topic_id
 *  Topic term tid.
 * @param array $fieldConditions
 *  Array of extra field conditions. Each item needs to be an array containing
 * the following keys:
 *    - field
 *    - column (optional)
 *    - value (optional)
 *    - operator (optional)
 *
 * @return int
 *  The count query result.
 */
function _get_content_count_by_region($content_type, $region_id, $topic_id = NULL, $fieldConditions = []) {
  // @todo: refactor this function after all content types have field_region and field_mea_topic.
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', $content_type)
    ->propertyCondition('status', NODE_PUBLISHED);
  switch ($content_type) {
    case 'decision':
    case 'document':
      $regional_treaties = _get_regional_treaties($region_id, $topic_id) + [-1];
      $query->fieldCondition('field_treaty', 'target_id', $regional_treaties, 'IN');
      break;

    default:
      $query->fieldCondition('field_region', 'tid', $region_id);
      if (!empty($topic_id)) {
        $query->fieldCondition('field_mea_topic', 'tid', $topic_id);
      }
  }
  foreach ($fieldConditions as $condition) {
    $column = !empty($condition['column']) ? $condition['column'] : NULL;
    $value = !empty($condition['value']) ? $condition['value'] : NULL;
    $operator = !empty($condition['operator']) ? $condition['operator'] : NULL;
    $query->fieldCondition($condition['field'], $column, $value, $operator);
  }
  return $query->count()->execute();
}

/**
 * Builds the query for solr-based views.
 *
 * @param array $options
 *  Array of query options.
 *
 * @return array
 *  Array of query options as required by solr-based views.
 */
function _geographic_region_build_search_query(array $options) {
  $f = [];
  foreach ($options as $key => $value) {
    if (!empty($value)) {
      $f[] = "$key:$value";
    }
  }
  return $f;
}

/**
 * Retrieves the region id contextual filter if available.
 *
 * @return null|int
 *  Region term tid.
 */
function _geographic_region_page_get_region_argument() {
  $page = page_manager_get_current_page();
  if (!empty($page['contexts']['argument_term_1']->argument)) {
    return $page['contexts']['argument_term_1']->argument;
  }
  return NULL;
}

/**
 * Implements hook_block_view().
 */
function geographic_region_block_view($delta = '') {
  $block = [];
  switch ($delta) {
    case 'region_page_title':
      $region_id = _geographic_region_page_get_region_argument();
      if (!empty($region_id)) {
        $vocabulary = taxonomy_vocabulary_machine_name_load('geographical_region');
        $terms = entity_load('taxonomy_term', FALSE, ['vid' => $vocabulary->vid]);
        $options = [];
        foreach ($terms as $term) {
          if ($term->tid == $region_id) {
            $title = sprintf('%s <span class="sr-only">%s</span>', t('Discover Environmental Information Concerning'), $term->name);
          }
          $options[url('/taxonomy/term/' . $term->tid)] = $term->name;
        }
        if (!empty($options)) {
          $block['content'] = [
            '#type' => 'select',
            '#options' => $options,
            '#default_value' => url('/taxonomy/term/' . $region_id),
            '#prefix' => '<h1>' . $title . '</h1>',
            '#attributes' => ['onChange' => 'window.location.href=this.value'],
            '#select2' => [
              'width' => 'auto',
            ],
          ];
        }
      }
      break;

    case 'region_switch_topic':
      $region_id = _geographic_region_page_get_region_argument();
      if (!empty($region_id)) {
        $page = page_manager_get_current_page();
        $vocabulary = taxonomy_vocabulary_machine_name_load('mea_topic');
        $terms = entity_load('taxonomy_term', FALSE, ['vid' => $vocabulary->vid]);
        usort($terms, function ($a, $b) {
          return strcmp($a->name, $b->name);
        });

        $current_topic = !empty($page['contexts']['argument_term_2']->argument)
          ? $page['contexts']['argument_term_2']->argument
          : NULL;

        $region_path = 'regions/' . $page['contexts']['argument_term_1']->original_argument;
        $tabs = [
          [
            'data' => l(t('All topics'), $region_path),
            'class' => empty($current_topic) ? ['active', 'all-topics'] : ['all-topics'],
          ],
        ];
        foreach ($terms as $term) {
          $tabs[] = [
            'data' => l($term->name, $region_path . '/' . $term->name),
            'class' => !empty($current_topic) && $current_topic == $term->tid ? ['active'] : [],
          ];
        }
        if (!empty($tabs) && count($tabs) > 1) {
          $block['content'] = [
            '#theme' => 'item_list',
            '#items' => $tabs,
            '#attributes' => ['class' => ['nav nav-tabs']],
          ];
        }
      }
      break;

    case 'region_downloadable_documents':
      $region_id = _geographic_region_page_get_region_argument();
      if (!empty($region_id)) {
        $page = page_manager_get_current_page();
        $topic = $page['contexts']['argument_term_2']->argument;
        $search_query = _geographic_region_build_search_query([
          'field_region' => $region_id,
          'field_topic' => $topic,
        ]);
        $sections = _region_downloadable_documents_block_get_sections();
        $list = [];
        foreach ($sections as $section) {
          $subList = [['data' => $section['title'], 'class' => ['section-title']]];
          foreach ($section['items'] as $title => $options) {
            $count = _get_content_count_by_region($options['type'], $region_id, $topic, !empty($options['fieldConditions']) ? $options['fieldConditions'] : []);
            if (!empty($count)) {
              $subList[] = [
                'data' => l(
                  sprintf('%s (%s)', $title, $count),
                  'search',
                  ['query' => ['f' => array_merge($search_query, ['type:' . $options['type']])]]
                ),
              ];
            }
          }
          if (count($subList) > 1) {
            $list = array_merge($list, $subList);
          }
        }
        if (!empty($list)) {
          $block['content'] = [
            '#theme' => 'item_list',
            '#items' => $list,
            '#attributes' => ['class' => ['nav']],
          ];
        }
      }
      break;
  }
  return $block;
}

/**
 * Implements hook_taxonomy_term_view().
 */
function geographic_region_taxonomy_term_view($term, $view_mode, $langcode) {
  if ($view_mode == 'full') {
    $vocabulary = taxonomy_vocabulary_machine_name_load('geographical_region');
    if ($term->vid == $vocabulary->vid) {
      // Redirect the default term page to region panel page.
      drupal_goto('regions/' . strtolower(str_replace(' ', '-', $term->name_original)));
    }
  }
}

function _region_downloadable_documents_block_get_sections() {
  return [
    [
      'title' => t('Treaties documents'),
      'items' => [
        t('Meetings decisions') => ['type' => 'decision'],
        t('COP Reports') => [
          'type' => 'document',
          'fieldConditions' => [
            [
              'field' => 'field_document_type',
              'column' => 'tid',
              'value' => [3131, 3132],
              'operator' => 'IN',
            ],
          ],
        ],
      ],
    ],
    [
      'title' => t('National submissions'),
      'items' => [
        t('National Action Plans') => ['type' => 'action_plan'],
        t('National Reports') => ['type' => 'national_report'],
      ],
    ],
    [
      'title' => t('National legislation and cases'),
      'items' => [
        t('National Legislation') => ['type' => 'legislation'],
        t('Court Decisions') => ['type' => 'court_decisions'],
      ],
    ],
    [
      'title' => t('Literature documents'),
      'items' => [
        t('Publications') => ['type' => 'literature'],
        t('Manuals') => [
          'type' => 'document',
          'fieldConditions' => [
            [
              'field' => 'field_document_type',
              'column' => 'tid',
              'value' => 3178,
            ],
          ],
        ],
        t('Technical Series') => [
          'type' => 'document',
          'fieldConditions' => [
            [
              'field' => 'field_document_type',
              'column' => 'tid',
              'value' => 2817,
            ],
          ],
        ],
      ],
    ],
  ];
}
