<?php
/**
 * @file
 * informea_search.features.fe_block_settings.inc
 */

/**
 * Implements hook_default_fe_block_settings().
 */
function informea_search_default_fe_block_settings() {
  $export = array();

  $export['version'] = '2.0';

  $export['facetapi-0Fv8Yf7yPH1f1s19610XqH66cbXO0IbH'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '0Fv8Yf7yPH1f1s19610XqH66cbXO0IbH',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'informea_theme' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'informea_theme',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Decision type',
    'visibility' => 0,
  );

  $export['facetapi-0Zc331B9jGDF3c2WiWkg3fJ10DgXAor0'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '0Zc331B9jGDF3c2WiWkg3fJ10DgXAor0',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'informea_theme' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'informea_theme',
        'weight' => -48,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Geographical scope',
    'visibility' => 0,
  );

  $export['facetapi-0faEepcyWgbiJ2byxWHum0bHgu6XcrI8'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '0faEepcyWgbiJ2byxWHum0bHgu6XcrI8',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'informea_theme' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'informea_theme',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-13ydV0i4Udr7KTwe85M05fQXGpthlfVI'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '13ydV0i4Udr7KTwe85M05fQXGpthlfVI',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'informea_theme' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'informea_theme',
        'weight' => -27,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '<none>',
    'visibility' => 0,
  );

  $export['facetapi-18bE3j8zhJo80qxLPcnj5t1bNCQ3uXbt'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '18bE3j8zhJo80qxLPcnj5t1bNCQ3uXbt',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'informea_theme' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'informea_theme',
        'weight' => -52,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Authors',
    'visibility' => 0,
  );

  $export['facetapi-1eJjUfjaQzB2kcDDuczwhpFt4oxmrpO2'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '1eJjUfjaQzB2kcDDuczwhpFt4oxmrpO2',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'informea_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'informea_theme',
        'weight' => -56,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Type',
    'visibility' => 0,
  );

  $export['facetapi-1wXV1njeL6I1brfjc2OlIuMhhhOfDhn0'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '1wXV1njeL6I1brfjc2OlIuMhhhOfDhn0',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'informea_theme' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'informea_theme',
        'weight' => -46,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Lead Institution',
    'visibility' => 0,
  );

  $export['facetapi-31Rw85UkyaDcz6GAwbNinJuzmfNuGM0q'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '31Rw85UkyaDcz6GAwbNinJuzmfNuGM0q',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'informea_theme' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'informea_theme',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-6S6Nx0Zd7h0gisYT18V8BvcC0Q1k5rhm'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '6S6Nx0Zd7h0gisYT18V8BvcC0Q1k5rhm',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'informea_theme' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'informea_theme',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Type',
    'visibility' => 0,
  );

  $export['facetapi-9wrQU80gNrEzbw1Ie31YkCYHc2sJOz02'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '9wrQU80gNrEzbw1Ie31YkCYHc2sJOz02',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'informea_theme' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'informea_theme',
        'weight' => -29,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '<none>',
    'visibility' => 0,
  );

  $export['facetapi-DDJOxOKhaPZkMK1hcpYUc1sQMHdOXWOJ'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'DDJOxOKhaPZkMK1hcpYUc1sQMHdOXWOJ',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'informea_theme' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'informea_theme',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-FhggtFZUQXw7XRePgNuXg1p9x7vgBSwG'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'FhggtFZUQXw7XRePgNuXg1p9x7vgBSwG',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'informea_theme' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'informea_theme',
        'weight' => -26,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '<none>',
    'visibility' => 0,
  );

  $export['facetapi-LWJWj4tpuIqEkT4y81zNVtf1iWZxryOt'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'LWJWj4tpuIqEkT4y81zNVtf1iWZxryOt',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'informea_theme' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'informea_theme',
        'weight' => -43,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Status',
    'visibility' => 0,
  );

  $export['facetapi-Lf1UodtmgEv6QpBb0FJQS6GtNsXVqBat'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'Lf1UodtmgEv6QpBb0FJQS6GtNsXVqBat',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'informea_theme' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'informea_theme',
        'weight' => -51,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Data source',
    'visibility' => 0,
  );

  $export['facetapi-PKmIxEaqDpK0PbGDdRV52A7jtupTOImx'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'PKmIxEaqDpK0PbGDdRV52A7jtupTOImx',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'informea_theme' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'informea_theme',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Type',
    'visibility' => 0,
  );

  $export['facetapi-PWq6fh33hqvAZzO5pGxs8RsAmjTxWVM0'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'PWq6fh33hqvAZzO5pGxs8RsAmjTxWVM0',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'informea_theme' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'informea_theme',
        'weight' => -50,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Field of application',
    'visibility' => 0,
  );

  $export['facetapi-TdG3Iyyz9a1NaJQLnx5LtArNQ2I8reiw'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'TdG3Iyyz9a1NaJQLnx5LtArNQ2I8reiw',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'informea_theme' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'informea_theme',
        'weight' => -24,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Date of text',
    'visibility' => 0,
  );

  $export['facetapi-UqhCTE3MjCqowbOaw2O2fSYBGezSv1VZ'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'UqhCTE3MjCqowbOaw2O2fSYBGezSv1VZ',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'informea_theme' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'informea_theme',
        'weight' => -45,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Parent',
    'visibility' => 0,
  );

  $export['facetapi-VzVADfHll1Di4dJ0NTJ2fvj7JjCVvcF5'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'VzVADfHll1Di4dJ0NTJ2fvj7JjCVvcF5',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'informea_theme' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'informea_theme',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-W1Sc0UqAaNsAxM01kwyS03BnpbbBtNUH'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'W1Sc0UqAaNsAxM01kwyS03BnpbbBtNUH',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'informea_theme' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'informea_theme',
        'weight' => -49,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'GEG Theme',
    'visibility' => 0,
  );

  $export['facetapi-b01M97N8OapCER3mxeFQvYWX9aRdHkkT'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'b01M97N8OapCER3mxeFQvYWX9aRdHkkT',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'informea_theme' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'informea_theme',
        'weight' => -28,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '<none>',
    'visibility' => 0,
  );

  $export['facetapi-lU0kkFRnzyJwsn07slk30R16Sy1xsgyf'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'lU0kkFRnzyJwsn07slk30R16Sy1xsgyf',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'informea_theme' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'informea_theme',
        'weight' => -25,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Glossary terms',
    'visibility' => 0,
  );

  $export['facetapi-pY6nQrARjEae1htfVD1sR1Rz0es9Sj2l'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'pY6nQrARjEae1htfVD1sR1Rz0es9Sj2l',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'informea_theme' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'informea_theme',
        'weight' => -47,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Kind',
    'visibility' => 0,
  );

  $export['facetapi-q1q1IaIhHLNp0RNuu5q553Ys9RNsdvdq'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'q1q1IaIhHLNp0RNuu5q553Ys9RNsdvdq',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'informea_theme' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'informea_theme',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Status',
    'visibility' => 0,
  );

  $export['facetapi-sNWAkwDKbo6AMe8WfxK9HaDMjxg7LWWD'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'sNWAkwDKbo6AMe8WfxK9HaDMjxg7LWWD',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'informea_theme' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'informea_theme',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-tlTj0HRgL67B2gv0e9ATKQRzacTbVHmt'] = array(
    'cache' => -1,
    'delta' => 'tlTj0HRgL67B2gv0e9ATKQRzacTbVHmt',
    'i18n_block_language' => array(),
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'informea_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'informea_theme',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
  );

  $export['facetapi-v41eJbSwkglIqPnH3Ny5ME63BDlFKzyC'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'v41eJbSwkglIqPnH3Ny5ME63BDlFKzyC',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'informea_theme' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'informea_theme',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Type of text',
    'visibility' => 0,
  );

  $export['facetapi-vS0iz2hKycgOtcX26OSG7x0gpn1kwjKI'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'vS0iz2hKycgOtcX26OSG7x0gpn1kwjKI',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'informea_theme' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'informea_theme',
        'weight' => -44,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'SDG Goals',
    'visibility' => 0,
  );

  $export['facetapi-ypESKm0EYw6ifS0RNyizmzoFDbTH6rZf'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'ypESKm0EYw6ifS0RNyizmzoFDbTH6rZf',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'informea_theme' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'informea_theme',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Jurisdiction',
    'visibility' => 0,
  );

  $export['facetapi-zjNTmpdt4IOvmxve1cQtB8i5B3CCWToQ'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'zjNTmpdt4IOvmxve1cQtB8i5B3CCWToQ',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'informea_theme' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'informea_theme',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Territorial subdivision',
    'visibility' => 0,
  );

  return $export;
}
